export const FETCH_TODOS = "FETCH_TODOS";
export const FETCH_TODOS_SUCCEED = "FETCH_TODOS_SUCCEED";
export const CREATE_TODO_SUCCEED = "CREATE_TODO_SUCCEED";
export const UPDATE_TODO = "UPDATE_TODO";
export const UPDATE_TODO_SUCCEED = "UPDATE_TODO_SUCCEED";
export const DELETE_TODO = "DELETE_TODO";
export const REMOVE_COMPLETED_TODOS = "REMOVE_COMPLETED_TODOS";
export const UPDATE_VISIBILITY = "UPDATE_VISIBILITY";
